config/routes.rb
Rails.application.routes.draw do
  resources :returs do
    member do
      get "getPengeluaran", to: "returs#getPengeluaran"
    end
  end
  resources :sale_histories
  resources :stock_opnames
  resources :sale_items

  resources :project_items do
    member do
      get 'getNamaBarang', to: 'project_items#getNamaBarang'
    end
  end
  resources :maintenance_assets
  resources :projects
  mount Notifications::Engine => "/notifications"
  get "getKodeBiaya", to: "sales#getKodeBiaya"
  get 'notifications/index'


  resources :divisions do
    collection do
      post 'migratedivisi', to:'divisions#migrateDivisi'
    end
  end

  resources :receive_histories do
    member do
      get "detailList", to: "receive_histories#detailList"
    end
  end
  resources :divisions
  get 'items_imports/new'
  get 'items_imports/create'
  devise_for :users, controllers: { sessions: 'users/sessions' }
  resources :users, :roles, :warehouses, :measurements, :item_groups, :divisions,
            :receive_process, :receive_kadep_supply_items

  resources :receives do
    member do
      get "getSpesifikasiBarang", to: "receives#getSpesifikasiBarang"
      get "exports", to: "receives#exports"
      # get "get_receive_data_nama_proyek", to: "receives#get_receive_data_nama_proyek"
      # get "get_kode_akun", to: "receives#get_kode_akun"
    end
  end


  resources :sales do 
    member do
      get "getNamaAkun", to: "sales#getNamaAkun"
      get "getNamaProjekOrProgram", to: "sales#getNamaProjekOrProgram"
      get "getDetailReceiveItem", to: "sales#getDetailReceiveItem"
    end
  end

  get "receives/search_kode_proyek"
  # start for autocomplete feature
  get "search_kode_proyek", to: "auto_completes#search_kode_proyek"
  get "search_kode_program", to: "auto_completes#search_kode_program"
  get "search_kode_proyek_for_project", to: "auto_completes#search_kode_proyek_for_project"
  get 'kode_proyek_for_maintenance', to: 'auto_completes#kode_proyek_for_maintenance'
  get "autocomplete/search_vendor", to: 'auto_completes#search_vendor'
  # get "search_owner", to: "auto_completes#search_owner"
  # end for autocomplete feature

  resources :receive_items do
    collection do

      get 'editSaleItem/:id', to: 'receive_items#edit_sale_item', as: 'edit_sale_item'
      patch 'updateSaleItem/:id', to: 'receive_items#update_sale_item', as: 'update_sale_item'
    end
  end

  resources :items do
    collection do
      post :import
    end
    member do
      get "tambahMasterBarang", to: "items#tambahMasterBarang"
    end
  end

  get 'detailApproval/:id', to: 'receive_process#index', as: 'detailApproval'
  get 'inputRack/:id', to: 'receive_process#input_rack', as: 'inputRack'
  get 'editRack/:id', to: 'receive_process#edit_rack', as: 'editRack'
  get 'editSaleItem/:id', to: 'sale_process#editSaleItem', as: 'editSaleItem'
  get 'editJumlahDikeluarkan/:id', to: 'sale_process#editJumlahDikeluarkan', as: 'editJumlahDikeluarkan'
  get 'receive_items/edit/:id/:receive_id',  to: 'receive_items#edit', as: 'receive_item_edit'
  post 'receive_process/setStatus'
  post 'receive_process/setLokasiPenempatan'
  post 'receive_process/printQRCode'
  post 'receive_process/setPosting'
  post 'receive_process/sendStaffGudang'
  post 'receive_process/confirmRejectKepalaGudangByAdmin'
  post 'items/saveMasterBarang'
  post 'sale_process/tambahBarang'
  post 'sale_process/updateItemBarang'
  post 'sale_process/submitUserTrading'
  post 'sale_process/updateJumlahDikeluarkan'
  post 'sale_process/submitStaffGudang'
  post 'sale_process/submitKepalaGudang'
  post 'sale_process/submitAdminPersediaan'
  post 'sale_process/submitKadepPersediaan'
  get "autocomplete/search_vendor", to: 'auto_completes#search_vendor'

  get 'receives/edit_receive_item' => 'receive_items#edit_receive_item'

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sale_history.rb
class SaleHistory < ApplicationRecord
  belongs_to :user
  belongs_to :status
  belongs_to :sale
  belongs_to :role, optional: true
end

app/controllers/sale_histories_controller.rb
class SaleHistoriesController < ApplicationController
  before_action :set_sale_history, only: %i[ show edit update destroy ]

  # GET /sale_histories or /sale_histories.json
  def index
    # @sale_histories = SaleHistory.all
    @sale_histories = SaleHistory.all
  end

  # GET /sale_histories/1 or /sale_histories/1.json
  def show
  end

  # GET /sale_histories/new
  def new
    @sale_history = SaleHistory.new
  end

  # GET /sale_histories/1/edit
  def edit
  end

  # POST /sale_histories or /sale_histories.json
  def create
    @sale_history = SaleHistory.new(sale_history_params)

    respond_to do |format|
      if @sale_history.save
        format.html { redirect_to @sale_history, notice: "Sale approval was successfully created." }
        format.json { render :show, status: :created, location: @sale_history }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sale_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sale_histories/1 or /sale_histories/1.json
  def update
    respond_to do |format|
      if @sale_history.update(sale_history_params)
        format.html { redirect_to @sale_history, notice: "Sale approval was successfully updated." }
        format.json { render :show, status: :ok, location: @sale_history }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sale_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sale_histories/1 or /sale_histories/1.json
  def destroy
    @sale_history.destroy
    respond_to do |format|
      format.html { redirect_to sale_histories_url, notice: "Sale approval was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale_history
      @sale_history = SaleHistory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sale_history_params
      params.require(:sale_history).permit(:catatan_penjualan, :user_id, :status_id, :sale_id, :role_id)
    end
end

app/views/sale_histories/_form.html.erb
<%= form_with(model: sale_history, local: true) do |form| %>
  <% if sale_history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sale_history.errors.count, "error") %> prohibited this sale_history from being saved:</h2>

      <ul>
      <% sale_history.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :catatan_penjualan %>
    <%= form.text_field :catatan_penjualan %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :status_id %>
    <%= form.text_field :status_id %>
  </div>

  <div class="field">
    <%= form.label :sale_id %>
    <%= form.text_field :sale_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sale_histories/edit.html.erb
<h1>Editing Sale Approval</h1>

<%= render 'form', sale_history: @sale_history %>

<%= link_to 'Show', @sale_history %> |
<%= link_to 'Back', sale_approvals_path %>

app/views/sale_histories/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="my-5 text-center font-weight-bolder">Approval Penjualan Barang</h1>

<% if current_user.roles.any? { |r| r.name == 'superadmin' || r.name == 'Staff Gudang' || r.name == 'Kepala Gudang' || r.name == 'Admin Persediaan' || r.name == 'Kepala Persediaan' } %>
<div class="row mx-0 px-5">
  <div class="table-responsive">
    <table class="table table-bordered" id="dataTable">
      <thead class="bg-primary">
      <tr class="text-center">
        <th>Catatan</th>
        <th>PIC</th>
        <th>Status Approval</th>
        <th>Nomor Penjualan</th>
        <th>Aksi</th>
      </tr>
      </thead>

      <tbody>
      <% @sale_histories.each do |sale_history| %>

        <% status = Status.find_by(id: sale_history.status) %>
        <% user = User.find_by(id: sale_history.user_id) %>
        <%# sale = Sale.find_by(id: sale_history.sale)%>
        <% if status.try(:nama_status) == 'pending review by admin persediaan' %>
        <tr>
        <td><%= sale_history.catatan_penjualan %></td>
          <td class="align-middle text-center"><%= user.try(:name) %></td>
          <td class="align-middle text-center">
            <button class='btn btn-warning font-weight-bolder btn-sm py-1 mb-1 px-2' disabled>
              <%= status.try(:nama_status) %>
            </button></td>
          <td class="align-middle text-center"><%= sale_history.nomor_penjualan %></td>
          <td class="align-middle text-center">
            <%= link_to sale_history,  class:"btn btn-warning btn-sm rounded-circle text-white py-1 mb-1 px-2" do  %>
              <i class="fas fa-eye"></i>
            <% end %>
            <%#= link_to edit_sale_path(sale_history),  class:"btn btn-success btn-sm rounded-circle text-white py-1 mb-1 px-2" do  %>
<!--              <i class="fas fa-pencil-alt"></i>-->
            <%# end %>
          </td>
        </tr>

          <% elsif status.try(:nama_status) == 'pending review by kadep persediaan' %>
          <tr>
            <td><%= sale_history.catatan_penjualan %></td>
            <td class="align-middle text-center"><%= user.try(:name) %></td>
            <td class="align-middle text-center">
              <button class='btn btn-warning font-weight-bolder btn-sm py-1 mb-1 px-2' disabled>
                <%= status.try(:nama_status) %>
              </button></td>
            <td class="align-middle text-center"><%= sale_history.nomor_penjualan %></td>
            <td class="align-middle text-center">
              <%= link_to sale_history,  class:"btn btn-warning btn-sm rounded-circle text-white py-1 mb-1 px-2" do  %>
                <i class="fas fa-eye"></i>
              <% end %>
              <%#= link_to edit_sale_path(sale_history),  class:"btn btn-success btn-sm rounded-circle text-white py-1 mb-1 px-2" do  %>
              <!--              <i class="fas fa-pencil-alt"></i>-->
              <%# end %>
            </td>
          </tr>
        <% elsif status.try(:nama_status) == 'pending review by staff gudang' %>
          <tr>
            <td><%= sale_history.catatan_penjualan %></td>
            <td class="align-middle text-center"><%= user.try(:name) %></td>
            <td class="align-middle text-center">
              <button class='btn btn-warning font-weight-bolder btn-sm py-1 mb-1 px-2' disabled>
                <%= status.try(:nama_status) %>
              </button></td>
            <td class="align-middle text-center"><%= sale_history.nomor_penjualan %></td>
            <td class="align-middle text-center">
              <%= link_to sale_history,  class:"btn btn-warning btn-sm rounded-circle text-white py-1 mb-1 px-2" do  %>
                <i class="fas fa-eye"></i>
              <% end %>
              <%#= link_to edit_sale_path(sale_history),  class:"btn btn-success btn-sm rounded-circle text-white py-1 mb-1 px-2" do  %>
              <!--              <i class="fas fa-pencil-alt"></i>-->
              <%# end %>
            </td>
          </tr>
        <% elsif status.try(:nama_status) == 'pending review by kepala gudang' %>
          <tr>
            <td><%= sale_history.catatan_penjualan %></td>
            <td class="align-middle text-center"><%= user.try(:name) %></td>
            <td class="align-middle text-center">
              <button class='btn btn-warning font-weight-bolder btn-sm py-1 mb-1 px-2' disabled>
                <%= status.try(:nama_status) %>
              </button></td>
            <td class="align-middle text-center"><%= sale_history.nomor_penjualan %></td>
            <td class="align-middle text-center">
              <%= link_to sale_history,  class:"btn btn-warning btn-sm rounded-circle text-white py-1 mb-1 px-2" do  %>
                <i class="fas fa-eye"></i>
              <% end %>
              <%#= link_to edit_sale_path(sale_history),  class:"btn btn-success btn-sm rounded-circle text-white py-1 mb-1 px-2" do  %>
              <!--              <i class="fas fa-pencil-alt"></i>-->
              <%# end %>
            </td>
          </tr>
        <% end %>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

<% end %>

app/views/sale_histories/new.html.erb
<h1>New Sale Approval</h1>

<%= render 'form', sale_history: @sale_history %>

<%= link_to 'Back', sale_approvals_path %>

app/views/sale_histories/show.html.erb
<p id="notice"><%= notice %></p>

<h1 class="my-5 text-center font-weight-bolder">Pengeluaran Barang Penjualan</h1>

<div class="row mx-5 mb-3">
  <h5 class="my-5 text-center font-weight-bolder">Input Pengeluaran Barang Penjualan</h5>
  <div class="col-12">
    <div class="navbar navbar-expand-sm menu-bar">
      <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item" role="presentation">
          <a class="nav-link active" id="data-pengeluaran-penjualan-tab" data-toggle="tab" href="#data-pengeluaran-penjualan" role="tab" aria-controls="data-pengeluaran" aria-selected="true">Data Pengeluaran</a>
        </li>
        <li class="nav-item" role="presentation">
          <a class="nav-link" id="data-barang-pengeluaran-penjualan-tab" data-toggle="tab" href="#data-barang-pengeluaran-penjualan" role="tab" aria-controls="data-barang" aria-selected="false">Data Barang</a>
        </li>
      </ul>
    </div>
  </div>
</div>

<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active" id="data-pengeluaran-penjualan" role="tabpanel" aria-labelledby="data-pengeluaran-penjualan-tab">
    <div class="row mx-0 px-5">
      <div class="container py-4 px-5">

        <div class="mb-3 row">
          <label for="" class="col-sm-4 col-form-label font-weight-bolder">Tanggal Pengeluaran </label>
          <div class="col-sm-8">
            <input type="text" class="form-control" value="<%= @sale.tanggal_penjualan %>" readonly>
          </div>
        </div>

        <div class="mb-3 row">
          <label for="" class="col-sm-4 col-form-label font-weight-bolder">Jenis Pengeluaran</label>
          <div class="col-sm-8">
            <input type="text" class="form-control" id="jenis_pengeluaran" value="<%= @sale.jenis_pengeluaran %>" readonly>
          </div>
        </div>

        <div class="mb-3 row">
          <label for="" class="col-sm-4 col-form-label font-weight-bolder">Nama Inputer</label>
          <div class="col-sm-8">
            <input type="text" class="form-control" id="jenis_pengeluaran" value="<%= @sale.nama_inputer %>" readonly>
          </div>
        </div>

        <div class="mb-3 row">
          <label for="" class="col-sm-4 col-form-label font-weight-bolder">Jenis Kode Biaya</label>
          <div class="col-sm-8">
            <input type="text" class="form-control" id="jenis_pengeluaran" value="<%= @sale.jenis_kode_biaya %>" readonly>
          </div>
        </div>

        <div class="mb-3 row" id="kode-program-fast">
          <label for="" class="col-sm-4 col-form-label font-weight-bolder">Kode Program Fast</label>
          <div class="col-sm-8">
            <input type="text" class="form-control" value="<%= @sale.kode_program_fast %>" readonly>
          </div>
        </div>

        <div class="mb-3 row" id="nama-program-fast">
          <label for="" class="col-sm-4 col-form-label font-weight-bolder">Nama Program Fast</label>
          <div class="col-sm-8">
            <input type="text" class="form-control" value="<%= @sale.nama_program_fast %>" readonly>
          </div>
        </div>

        <div class="mb-3 row" id="">
          <label for="" class="col-sm-4 col-form-label font-weight-bolder">keterangan Pengeluaran</label>
          <div class="col-sm-8">
            <textarea name="" id="" cols="30" rows="10" class="form-control" readonly><%= @sale.keterangan_penjualan %></textarea>
          </div>
        </div>

        <div class="mb-3 row">
          <label for="" class="col-sm-4 col-form-label font-weight-bolder">Dokumen Penjualan</label>
          <div class="col-sm-8">
            <% if @sale.dokumen_penjualan.blank? %>
              <h5 class="text-danger">tidak ada dokumen yg di upload</h5>
            <%  else  %>
              <% @sale.dokumen_penjualan.each do |d|  %>
                <%=  text_field :sale, :dokumen_penjualan, multiple: true, value: d.identifier, class:"form-control", :readonly => true  %>
                <%=  link_to "Download disini", @sale.dokumen_penjualan[0].url, :target => "_blank"  %>
              <%  end  %>
            <%  end %>
          </div>
        </div>

        <div class="mb-3 justify-content-md-end">
          <%#= link_to 'Back', sales_path, class:"btn btn-warning text-white btn-custom rounded-pill" %>
          <%#= link_to 'Edit', edit_sale_path(@sale), class:"btn btn-info text-white btn-custom rounded-pill mr-2" %>
        </div>
      </div>
    </div>
  </div>
  <div class="tab-pane fade" id="data-barang-pengeluaran-penjualan" role="tabpanel" aria-labelledby="data-barang-pengeluaran-penjualan-tab">
    <div class="row mx-0 px-5">
      <button type="button" class="btn btn-primary btn-custom rounded-pill mr-md-2" data-toggle="modal" data-target="#tambahBarangPengeluaran">tambah barang</button>
      <div class="col-12">
        <br>
        <div class="table-responsive">
          <table class="table table-bordered" id="dataTable">
            <thead class="bg-primary">
            <tr class="text-center">
              <th class="align-middle" style="width: 8%;">Kode Barang</th>
              <th class="align-middle" style="width: 24%;">Nama Barang</th>
              <th class="align-middle" style="width: 7%;">Satuan</th>
              <th class="align-middle" style="width: 11%;">Jumlah Tersedia</th>
              <% if current_user.roles.any? { |r| r.id == 1 || r.id == 8 } %>
                <th class="align-middle" style="width: 11%;">Jumlah Dikeluarkan</th>
                <th class="align-middle" style="width: 11%;">Lokasi Penempatan</th>
              <% end %>
              <th class="align-middle" style="width: 7%;">Gudang</th>
              <th class="align-middle" style="width: 10%;">Aksi</th>
            </tr>
            </thead>
            <% @sale_items.each do |sale_item| %>
              <tbody>
              <% item = Item.find_by(id: sale_item.item)%>
              <% item_measurement = Measurement.find_by(id: sale_item.measurement_id) %>
              <% warehouse = Warehouse.find_by(id: sale_item.warehouse) %>
              <tr>
                <td class="align-middle"><%= item.try(:kode_barang) %></td>
                <td class="align-middle"><%= item.try(:nama_barang) %></td>
                <td class="align-middle"><%= item_measurement.try(:nama_satuan) %></td>
                <td class="align-middle"><%= sale_item.jumlah_tersedia %></td>
                <% if current_user.roles.any? { |r| r.id == 1 || r.id == 8 } %>
                  <td class="align-middle"><%= sale_item.jumlah_keluar %></td>
                  <td class="align-middle"><%= sale_item.lokasi_penempatan %></td>
                <% end %>
                <td class="align-middle"><%= warehouse.try(:nama_gudang) %></td>
                <td class="align-middle text-center">
                  <%= link_to edit_sale_item_path(sale_item), class:"btn btn-success btn-sm rounded-circle text-white py-1 mb-1 px-2" do  %>
                    <i class="fas fa-pencil-alt"></i>
                  <% end %>
                  <%= link_to sale_item, method: :delete, data:{ confirm: 'Apakah anda yakin ingin menghapus?'},remote: true, class:"btn btn-danger btn-sm rounded-circle text-white py-1 mb-1 px-2" do %>
                    <i class="fas fa-trash-alt"></i>
                  <% end %>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
        <br>
        <div class="d-grid gap-2 d-md-flex mx-5 mb-3 justify-content-md-end">
          <%= form_with(model: @sale, local: true) do |form| %>
            <% if @sale.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(sale.errors.count, "error") %> prohibited this sale from being saved:</h2>
                <ul>
                  <% sale.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
            <%= form.hidden_field :status_id, :value => 8, id: "status_id" %>
            <button class="btn btn-success btn-custom rounded-pill" type="submit">Submit</button>
          <% end %>
        </div>
      </div>
    </div>
<!--    <div class="modal fade" id="tambahBarangPengeluaran" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">-->
<!--      <div class="modal-dialog modal-dialog-centered modal-xl">-->
<!--        <div class="modal-content">-->
<!--          <div class="modal-header justify-content-md-center bg-gradient-primary">-->
<!--            <h5 class="modal-title text-white" id="editItemMaterialModalLabel">Tambah Pengeluaran Barang Penjualan</h5>-->
<!--          </div>-->
<!--          <div class="modal-body">-->
            <%#= form_for(@sale_item, url: sale_items_path, method: 'POST') do |form| %>
              <%# if @sale_item.errors.any? %>
<!--                <div id="error_explanation">-->
<!--                  <h2><%#= pluralize(sale_item.errors.count, "error") %> prohibited this sale_item from being saved:</h2>-->
<!--                  <ul>-->
                    <%# sale_item.errors.full_messages.each do |message| %>
<!--                      <li><%#= message %></li>-->
                    <%# end %>
<!--                  </ul>-->
<!--                </div>-->
              <%# end %>

<!--              <div class="mb-3 row">-->
<!--                <label for="" class="col-sm-4 col-form-label font-weight-bolder">Kode Barang</label>-->
<!--                <div class="col-sm-8">-->
                  <%#= form.collection_select :item_id, Item.all, :id, :kode_barang, {prompt: "pilih kode barang"}, class: "form-control", id:"kode-barang", onchange: "setNamaBarang()" %>
<!--                </div>-->
<!--              </div>-->

<!--              <div class="mb-3 row">-->
<!--                <label for="" class="col-sm-4 col-form-label font-weight-bolder">Nama Barang</label>-->
<!--                <div class="col-sm-8">-->
<!--                  <input type="text" class="form-control" id="nama-barang" readonly>-->
<!--                </div>-->
<!--              </div>-->

<!--              <div class="mb-3 row">-->
<!--                <label for="" class="col-sm-4 col-form-label font-weight-bolder">Satuan</label>-->
<!--                <div class="col-sm-8">-->
                  <%#= form.collection_select :measurement_id, Measurement.all, :id, :nama_satuan, { prompt: true }, class: "form-control" %>
<!--                </div>-->
<!--              </div>-->

<!--              <div class="mb-3 row">-->
                <%#= form.label :warehouse_id, "Nama Gudang", class: "col-sm-4 col-form-label font-weight-bolder" %>
<!--                <div class="col-sm-8">-->
                  <%#= form.collection_select :warehouse_id, Warehouse.all, :id, :nama_gudang, { prompt: true }, class: "form-control" %>
<!--                </div>-->
<!--              </div>-->

              <%# if current_user.roles.any? { |r| r.id == 1 || r.id == 8 } %>

<!--                <div class="mb-3 row">-->
<!--                  <label for="" class="col-sm-4 col-form-label font-weight-bolder">Lokasi Penempatan</label>-->
<!--                  <div class="col-sm-8">-->
                    <%#= form.text_field :lokasi_penempatan, class: "form-control" %>
<!--                  </div>-->
<!--                </div>-->

              <%# end %>
<!--              <div class="mb-3 row">-->
<!--                <label for="" class="col-sm-4 col-form-label font-weight-bolder">Jumlah Tersedia</label>-->
<!--                <div class="col-sm-8">-->
                  <%#= form.text_field :jumlah_tersedia, class: "form-control" %>
<!--                </div>-->
<!--              </div>-->

<!--                <div class="mb-3 row">-->
<!--                  <label for="" class="col-sm-4 col-form-label font-weight-bolder">Jumlah Keluar</label>-->
<!--                  <div class="col-sm-8">-->
                    <%#= form.number_field :jumlah_keluar, class: "form-control" %>
<!--                  </div>-->
<!--                </div>-->
<!--               Start Hidden Field Section -->
              <%#= form.hidden_field :sale_id, id: "sale_id", :value => @sale.id %>
<!--               Finish Hideed Field Section -->


<!--              <div class="modal-footer">-->
<!--                <button class="btn btn-info text-white btn-custom rounded-pill" type="submit">Simpan</button>-->
<!--              </div>-->
<!--              </div>-->
            <%# end %>
<!--            </div>-->
<!--      </div>-->
<!--    </div>-->
  </div>
</div>