config/routes.rb
Rails.application.routes.draw do
  resources :returs do
    member do
      get "getPengeluaran", to: "returs#getPengeluaran"
    end
  end
  resources :sale_histories
  resources :stock_opnames
  resources :sale_items

  resources :project_items do
    member do
      get 'getNamaBarang', to: 'project_items#getNamaBarang'
    end
  end
  resources :maintenance_assets
  resources :projects
  mount Notifications::Engine => "/notifications"
  get "getKodeBiaya", to: "sales#getKodeBiaya"
  get 'notifications/index'


  resources :divisions do
    collection do
      post 'migratedivisi', to:'divisions#migrateDivisi'
    end
  end

  resources :receive_histories do
    member do
      get "detailList", to: "receive_histories#detailList"
    end
  end
  resources :divisions
  get 'items_imports/new'
  get 'items_imports/create'
  devise_for :users, controllers: { sessions: 'users/sessions' }
  resources :users, :roles, :warehouses, :measurements, :item_groups, :divisions,
            :receive_process, :receive_kadep_supply_items

  resources :receives do
    member do
      get "getSpesifikasiBarang", to: "receives#getSpesifikasiBarang"
      get "exports", to: "receives#exports"
      # get "get_receive_data_nama_proyek", to: "receives#get_receive_data_nama_proyek"
      # get "get_kode_akun", to: "receives#get_kode_akun"
    end
  end


  resources :sales do 
    member do
      get "getNamaAkun", to: "sales#getNamaAkun"
      get "getNamaProjekOrProgram", to: "sales#getNamaProjekOrProgram"
      get "getDetailReceiveItem", to: "sales#getDetailReceiveItem"
    end
  end

  get "receives/search_kode_proyek"
  # start for autocomplete feature
  get "search_kode_proyek", to: "auto_completes#search_kode_proyek"
  get "search_kode_program", to: "auto_completes#search_kode_program"
  get "search_kode_proyek_for_project", to: "auto_completes#search_kode_proyek_for_project"
  get 'kode_proyek_for_maintenance', to: 'auto_completes#kode_proyek_for_maintenance'
  get "autocomplete/search_vendor", to: 'auto_completes#search_vendor'
  # get "search_owner", to: "auto_completes#search_owner"
  # end for autocomplete feature

  resources :receive_items do
    collection do

      get 'editSaleItem/:id', to: 'receive_items#edit_sale_item', as: 'edit_sale_item'
      patch 'updateSaleItem/:id', to: 'receive_items#update_sale_item', as: 'update_sale_item'
    end
  end

  resources :items do
    collection do
      post :import
    end
    member do
      get "tambahMasterBarang", to: "items#tambahMasterBarang"
    end
  end

  get 'detailApproval/:id', to: 'receive_process#index', as: 'detailApproval'
  get 'inputRack/:id', to: 'receive_process#input_rack', as: 'inputRack'
  get 'editRack/:id', to: 'receive_process#edit_rack', as: 'editRack'
  get 'editSaleItem/:id', to: 'sale_process#editSaleItem', as: 'editSaleItem'
  get 'editJumlahDikeluarkan/:id', to: 'sale_process#editJumlahDikeluarkan', as: 'editJumlahDikeluarkan'
  get 'receive_items/edit/:id/:receive_id',  to: 'receive_items#edit', as: 'receive_item_edit'
  post 'receive_process/setStatus'
  post 'receive_process/setLokasiPenempatan'
  post 'receive_process/printQRCode'
  post 'receive_process/setPosting'
  post 'receive_process/sendStaffGudang'
  post 'receive_process/confirmRejectKepalaGudangByAdmin'
  post 'items/saveMasterBarang'
  post 'sale_process/tambahBarang'
  post 'sale_process/updateItemBarang'
  post 'sale_process/submitUserTrading'
  post 'sale_process/updateJumlahDikeluarkan'
  post 'sale_process/submitStaffGudang'
  post 'sale_process/submitKepalaGudang'
  post 'sale_process/submitAdminPersediaan'
  post 'sale_process/submitKadepPersediaan'
  get "autocomplete/search_vendor", to: 'auto_completes#search_vendor'

  get 'receives/edit_receive_item' => 'receive_items#edit_receive_item'

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/receive_item.rb
class ReceiveItem < ApplicationRecord
  belongs_to :receive
  belongs_to :item
  belongs_to :warehouse
  belongs_to :measurement
  has_many :sale_item

  def kodeItem
    "#{self.item.kode_barang}" 
  end
end

app/controllers/receive_items_controller.rb
class ReceiveItemsController < ApplicationController
  before_action :set_receive_item, only: %i[ show edit update destroy ]

  # GET /receive_items or /receive_items.json
  def index
    @receive_items = ReceiveItem.order(:created_at)
  end

  # GET /receive_items/1 or /receive_items/1.json
  def show
  end

  def show_sale_item
  end

  # GET /receive_items/new
  def new
    @receive_item = ReceiveItem.new
  end

  # GET /receive_items/1/edit
  def edit
  end

  def edit_sale_item
    set_receive_item
    render :edit
  end


  # POST /receive_items or /receive_items.json
  def create
    @receive_item = ReceiveItem.new(receive_item_params)
    respond_to do |format|
      if @receive_item.save
        format.html { redirect_back(fallback_location: root_path)}
        # format.html { redirect_to @receive_item, notice: "Receive item was successfully created." }
        # format.json { render :show, status: :created, location: @receive_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @receive_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # def edit_receive_item
  #   respond_to do |format|
  #     format.html
  #     format.js
  #   end
  # end

  # PATCH/PUT /receive_items/1 or /receive_items/1.json
  def update
    respond_to do |format|
      if @receive_item.update(receive_item_params)
        if current_user.roles.any? { |r| r.name == 'Staff Gudang'}
          format.html { render :edit }
        else
          format.html { redirect_to receife_path(params[:receive_item][:receive_id]), notice: "Receive Item has updated" }
        end
      # elsif @receive_item.update(receive_item_params)
      #   format.html { redirect_back(fallback_location: proc { @sale})}
        # format.js { render inline: "goBack();" }

        # format.html { redirect_to @receive_item, notice: "Receive item was successfully updated." }
        # format.json { render :show, status: :ok, location: @receive_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @receive_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # def update_sale_item
  #   respond_to do |format|
  #     #todo mau pisahin ketika user update jmlh permintaan tampilnya kembali ke sales/show
  #     if @receive_item.update(params[:jumlah_permintaan])
  #       format.html { redirect_to receife_path(params[:receive_item][:receive_id]), notice: "Sale Item has updated" }
  #       # format.html { redirect_back(fallback_location: proc { @sale})}
  #       # format.js { render inline: "goBack();" }
  #
  #       # format.html { redirect_to @receive_item, notice: "Receive item was successfully updated." }
  #       # format.json { render :show, status: :ok, location: @receive_item }
  #     else
  #       format.html { render :edit, status: :unprocessable_entity }
  #       format.json { render json: @receive_item.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  # DELETE /receive_items/1 or /receive_items/1.json
  def destroy
    @receive_item = ReceiveItem.find(params[:id])
    @receive_item.destroy
    respond_to do |format|
      format.js { render inline: "location.reload();" }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_receive_item
    @receive_item = ReceiveItem.find(params[:id])
  end

    # Only allow a list of trusted parameters through.
  def receive_item_params
    params.require(:receive_item).permit(:receive_id, :item_id, :measurement_id, :harga_satuan,
                                         :jumlah_pesanan, :jumlah_terima, :jumlah_harga, :qr_code, :merek, :serial,
                                         :ukuran, :spesifikasi_barang, :lain, :tipe, :jumlah_permintaan, :jumlah_keluar,
                                         :status_item, :warehouse_id)
  end
end

app/helpers/receive_items_helper.rb
module ReceiveItemsHelper
end

app/views/receive_items/_form.html.erb
<%= form_with(model: receive_item, local: true) do |form| %>
  <% if receive_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(receive_item.errors.count, "error") %> prohibited this receive_item from being saved:</h2>

      <ul>
      <% receive_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row mx-0 px-5">
    <div class="container py-4 px-5">

          <div class="mb-3 row">
            <%= form.label :nama_barang, "Nama Barang", class: "col-sm-4 col-form-label" %>
            <div class="col-sm-8">
              <%= form.collection_select :item_id, Item.all, :id, :searchItem, {prompt: "pilih nama barang"}, class: "form-control", id:"staff", required: true %>
            </div>
          </div>

          <div class="mb-3 row">
            <%= form.label :measurement_id, "Satuan", class: "col-sm-4 col-form-label" %>
            <div class="col-sm-8">
              <%= form.collection_select :measurement_id, Measurement.all, :id, :nama_satuan, {prompt: "pilih satuan"}, class: "form-control" %>
            </div>
          </div>

          <div class="mb-3 row">
            <%= form.label :harga_satuan, "Harga Satuan", class: "col-sm-4 col-form-label" %>
            <div class="col-sm-8">
             <% if params[:id].present? %>
                <% getHargaSatuan = ReceiveItem.find(params[:id])%>
                <input type="text" class="form-control" value="<%= number_to_currency(getHargaSatuan.harga_satuan, unit: "Rp. ", separator: ",", delimiter: ".")%>" id="negoprice_result"/>
              <% else %>
                <input type="text" class="form-control" id="negoprice_result"/>
              <% end %>
              <%= form.hidden_field :harga_satuan, class: "form-control", id:"harga_satuan", required: true %>
            </div>
          </div>

          <div class="mb-3 row">
            <%= form.label :jumlah_pesanan, "Jumlah Pesanan", class: "col-sm-4 col-form-label" %>
            <div class="col-sm-8">
              <%= form.number_field :jumlah_pesanan, class: "form-control", required: true %>
            </div>
          </div>

          <div class="mb-3 row">
            <%= form.label :jumlah_terima, "Jumlah Diterima", class: "col-sm-4 col-form-label" %>
            <div class="col-sm-8">
              <%= form.number_field :jumlah_terima, class: "form-control", id:"jumlah_terima", required: true %>
              <%= form.hidden_field :jumlah_harga, class: "form-control", id:"jumlah_harga", required: true %>
            </div>
          </div>

        <%= form.hidden_field :receive_id, value: params[:receive_id] %>
      <%= form.hidden_field :status_item, value: "unchecked" %>

        <% if @receive_item.jumlah_terima.blank? and @receive_item.harga_satuan.blank? %>

          <% @getJumlahTerima = @receive_item.jumlah_terima.to_f %>
          <% @getHargaSatuan = @receive_item.harga_satuan.to_f %>
          <% @getJumlahHarga = @getJumlahTerima * @getHargaSatuan %>

        <% end %>

    </div>
  </div>

  <div class="col-sm-12">
    <div class="mb-3 float-right">
      <button class="btn btn-primary text-white btn-custom rounded-pill" data-dismiss="modal">Simpan</button>
    </div>
  </div>

<% end %>

<script>
  $("#harga_satuan, #jumlah_terima").keyup(function() {
      let harga_satuan = $("#harga_satuan").val();
      let jumlah_terima = $("#jumlah_terima").val();

      let jumlah_harga = parseInt(harga_satuan) * parseInt(jumlah_terima);
      $("#jumlah_harga").val(jumlah_harga);
  });

  $('#staff').select2();
  $('#negoprice_result').keyup(function(){
      var value = (this.value.replace(/[^\/\d]/g, ''));
      var bidprice = parseInt($('#clarification_negotiation_report_bidprice').val());
      var negoprice = parseInt(value);
      $('#harga_satuan').val(negoprice);
      this.value = rupiah_formater(value, 'Rp. ');
      var selisih = bidprice - negoprice;
      $('#clarification_negotiation_report_negoprice_bidpricecorrected_gap').val(selisih);
      selisih = selisih + "";
      selisih = (selisih.replace(/[^\/\d]/g, ''));
      selisih = rupiah_formater(selisih, 'Rp. ');
      $('#negoprice_bidpricecorrected_gap').val(selisih);
  });
  $('#negoprice_result').val(rupiah_formater($('#negoprice_result').val(), 'Rp. '));
</script>

app/views/receive_items/_form_sale_item.html.erb
<%= form_with(model: receive_item, local: true) do |form| %>
  <% if receive_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(receive_item.errors.count, "error") %> prohibited this receive_item from being saved:</h2>

      <ul>
      <% receive_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row mx-0 px-5">
    <div class="container py-4 px-5">

        <% if current_user.roles.any? { |r| r.name == 'User Komersial' } %>

        <div class="mb-3 row">
          <%= form.label :jumlah_permintaan, "Jumlah Permintaan", class: "col-sm-4 col-form-label" %>
          <div class="col-sm-8">
            <%= form.number_field :jumlah_permintaan, class: "form-control", required: true %>
          </div>
          <%= form.hidden_field :receive_id, value: @receive_item.receive_id %>
          <%= form.hidden_field :status_item, :value => 'checked', id: "status_item" %>
        </div>

      <% elsif current_user.roles.any? { |r| r.name == 'Staff Gudang' } %>

        <div class="mb-3 row">
          <%= form.label :jumlah_keluar, "Jumlah Dikeluarkan", class: "col-sm-4 col-form-label" %>
          <div class="col-sm-8">
            <%= form.number_field :jumlah_keluar, class: "form-control", required: true %>
          </div>
          <%= form.hidden_field :receive_id, value: @receive_item.receive_id %>
        </div>

      <% end %>

        <div class="col-sm-12">
          <div class="mb-3 float-right">
            <%= link_to 'Back', sales_path, class:"btn btn-secondary text-white btn-custom rounded-pill" %>
<!--            <button class="btn btn-secondary text-white btn-custom rounded-pill" onclick="history.back()">Kembali</button>-->

            <button class="btn btn-primary text-white btn-custom rounded-pill" data-dismiss="modal">Simpan</button>

          </div>
        </div>

    </div>
  </div>

<% end %>

app/views/receive_items/create.html.erb
<h1>ReceiveItems#create</h1>
<p>Find me in app/views/receive_items/create.html.erb</p>

app/views/receive_items/delete.html.erb
<h1>ReceiveItemsController#delete</h1>
<p>Find me in app/views/receive_items_controller/delete.html.erb</p>

app/views/receive_items/destroy.js.erb
$('#delete').bind('ajax:success', function (){
    $(this).closest('tr').fadeOut()
})

app/views/receive_items/edit.html.erb
<% if current_user.roles.any? { |r| r.name == 'User Komersial' } %>
  <h1 class="my-5 text-center font-weight-bolder">Input Jumlah Permintaan</h1>
  <%= render 'form_sale_item', receive_item: @receive_item %>
<% elsif current_user.roles.any? { |r| r.name == 'Staff Gudang' } %>
  <h1 class="my-5 text-center font-weight-bolder">Input Jumlah Dikeluarkan</h1>
  <%= render 'form_sale_item', receive_item: @receive_item %>
<% elsif current_user.roles.any? { |r| r.name == 'Admin Persediaan' } %>
  <h1 class="my-5 text-center font-weight-bolder">Edit Barang Penerimaan</h1>
  <%= render 'form', receive_item: @receive_item %>

<% end %>

app/views/receive_items/index.html.erb
<% unless notice.blank? %>
<div class="alert alert-success alert-dismissible fade show" role="alert">
  <strong id="notice"><%= notice %></strong>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<% end %>

<h1>Receive Items</h1>

<table>
  <thead>
    <tr>
      <th>Receive</th>
      <th>Item</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @receive_items.each do |receive_item| %>
      <tr>
        <td><%= receive_item.receive %></td>
        <td><%= receive_item.item %></td>
        <td><%= link_to 'Show', receive_item %></td>
        <td><%= link_to 'Edit', edit_receive_item_path(receive_item) %></td>
        <td><%= link_to 'Destroy', receive_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Receive Item', new_receive_item_path %>

app/views/receive_items/new.html.erb
<h1>New Receive Item</h1>

<%= render 'form', receive_item: @receive_item %>

<%= link_to 'Kembali', receive_items_path %>

app/views/receive_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Receive:</strong>
  <%= @receive_item.receive %>
</p>

<p>
  <strong>Item:</strong>
  <%= @receive_item.item %>
</p>

<%= link_to 'Edit', edit_receive_item_path(@receive_item) %> |
<%= link_to 'Kembali', receive_items_path %>

app/views/receive_items/update.html.erb
<h1>ReceiveItemsController#update</h1>
<p>Find me in app/views/receive_items_controller/update.html.erb</p>