config/routes.rb
Rails.application.routes.draw do
  resources :returs do
    member do
      get "getPengeluaran", to: "returs#getPengeluaran"
    end
  end
  resources :sale_histories
  resources :stock_opnames
  resources :sale_items

  resources :project_items do
    member do
      get 'getNamaBarang', to: 'project_items#getNamaBarang'
    end
  end
  resources :maintenance_assets
  resources :projects
  mount Notifications::Engine => "/notifications"
  get "getKodeBiaya", to: "sales#getKodeBiaya"
  get 'notifications/index'


  resources :divisions do
    collection do
      post 'migratedivisi', to:'divisions#migrateDivisi'
    end
  end

  resources :receive_histories do
    member do
      get "detailList", to: "receive_histories#detailList"
    end
  end
  resources :divisions
  get 'items_imports/new'
  get 'items_imports/create'
  devise_for :users, controllers: { sessions: 'users/sessions' }
  resources :users, :roles, :warehouses, :measurements, :item_groups, :divisions,
            :receive_process, :receive_kadep_supply_items

  resources :receives do
    member do
      get "getSpesifikasiBarang", to: "receives#getSpesifikasiBarang"
      get "exports", to: "receives#exports"
      # get "get_receive_data_nama_proyek", to: "receives#get_receive_data_nama_proyek"
      # get "get_kode_akun", to: "receives#get_kode_akun"
    end
  end


  resources :sales do 
    member do
      get "getNamaAkun", to: "sales#getNamaAkun"
      get "getNamaProjekOrProgram", to: "sales#getNamaProjekOrProgram"
      get "getDetailReceiveItem", to: "sales#getDetailReceiveItem"
    end
  end

  get "receives/search_kode_proyek"
  # start for autocomplete feature
  get "search_kode_proyek", to: "auto_completes#search_kode_proyek"
  get "search_kode_program", to: "auto_completes#search_kode_program"
  get "search_kode_proyek_for_project", to: "auto_completes#search_kode_proyek_for_project"
  get 'kode_proyek_for_maintenance', to: 'auto_completes#kode_proyek_for_maintenance'
  get "autocomplete/search_vendor", to: 'auto_completes#search_vendor'
  # get "search_owner", to: "auto_completes#search_owner"
  # end for autocomplete feature

  resources :receive_items do
    collection do

      get 'editSaleItem/:id', to: 'receive_items#edit_sale_item', as: 'edit_sale_item'
      patch 'updateSaleItem/:id', to: 'receive_items#update_sale_item', as: 'update_sale_item'
    end
  end

  resources :items do
    collection do
      post :import
    end
    member do
      get "tambahMasterBarang", to: "items#tambahMasterBarang"
    end
  end

  get 'detailApproval/:id', to: 'receive_process#index', as: 'detailApproval'
  get 'inputRack/:id', to: 'receive_process#input_rack', as: 'inputRack'
  get 'editRack/:id', to: 'receive_process#edit_rack', as: 'editRack'
  get 'editSaleItem/:id', to: 'sale_process#editSaleItem', as: 'editSaleItem'
  get 'editJumlahDikeluarkan/:id', to: 'sale_process#editJumlahDikeluarkan', as: 'editJumlahDikeluarkan'
  get 'receive_items/edit/:id/:receive_id',  to: 'receive_items#edit', as: 'receive_item_edit'
  post 'receive_process/setStatus'
  post 'receive_process/setLokasiPenempatan'
  post 'receive_process/printQRCode'
  post 'receive_process/setPosting'
  post 'receive_process/sendStaffGudang'
  post 'receive_process/confirmRejectKepalaGudangByAdmin'
  post 'items/saveMasterBarang'
  post 'sale_process/tambahBarang'
  post 'sale_process/updateItemBarang'
  post 'sale_process/submitUserTrading'
  post 'sale_process/updateJumlahDikeluarkan'
  post 'sale_process/submitStaffGudang'
  post 'sale_process/submitKepalaGudang'
  post 'sale_process/submitAdminPersediaan'
  post 'sale_process/submitKadepPersediaan'
  get "autocomplete/search_vendor", to: 'auto_completes#search_vendor'

  get 'receives/edit_receive_item' => 'receive_items#edit_receive_item'

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :status
  belongs_to :receive
  has_one :user
  has_many :sale_items, dependent: :destroy
  has_many :sale_history, dependent: :destroy
  # has_many :receive_items
  # belongs_to :receive
  mount_uploaders :dokumen_penjualan, SaleUploader
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: %i[ show edit update destroy ]
  include SalesHelper

  # GET /sales or /sales.json

  def getDetailReceiveItem
    kode_barang = params[:id]
    render json: ReceiveItem.select('*')
                        .where('item_id = ?', kode_barang)
                        .map{ |vendor|
                            {:idreceiveitem => vendor.id, :idmeasurement => vendor.measurement_id, :idwarehouse => vendor.warehouse_id, :qrcode => vendor.qr_code, :satuan => vendor.measurement.nama_satuan, :lokasipenempatan => vendor.lokasi_penempatan, :lokasigudang => vendor.warehouse.nama_gudang, :jumlahtersedia => vendor.jumlah_terima}
                        }
  end

  def getNamaAkun
    kode_barang = params[:id]
    uri = URI.parse('http://192.168.60.136:3000/fast/akuns/akunPersediaan')
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = false
    request = Net::HTTP::Get.new(uri.request_uri)
    request['Authorization'] = 'Bearer 4854b5b486f4159566c80d842850b967'
    response = http.request(request)

    parsed = JSON.parse(response.body)
    f = {}
    parsed['result']['data'].each do |e|
      if e['kode'].to_s.match(/^#{kode_barang}$/)
        f["#{e['deskripsi']}"] = "#{e['deskripsi']}"
      end
    end

    f.sort_by { |key| key }

    render json:  f.map {|k,v|
                    {:value => v[k]} #[k] digunakan untuk distinct duplikasi data pada array
                  }
  end

  def getNamaProjekOrProgram
    kode_barang = params[:id]
    render json: Receive.select('*')
                        .where('kode_proyek LIKE ?', "%#{kode_barang}%")
                        .map{ |vendor|
                            {:value => vendor.nama_proyek, :kode_akun => vendor.kode_akun}
                        }
  end

  def index
    getRole = RoleAssignment.find_by_user_id(current_user.id)
    if current_user.roles.any? { |r| r.name == 'User Trading' }
      @sales = Sale.order(:created_at)
    elsif current_user.roles.any? { |r| r.name == 'Staff Gudang' }
      @sales = SaleHistory.where(role_id: getRole.role_id).select('DISTINCT ON (sale_id) *').order('sale_id DESC, created_at DESC')
    elsif current_user.roles.any? { |r| r.name == 'Kepala Gudang' }
      @sales = SaleHistory.where(role_id: getRole.role_id).select('DISTINCT ON (sale_id) *').order('sale_id DESC, created_at DESC')
    elsif current_user.roles.any? { |r| r.name == 'Admin Persediaan' }
      @sales = Sale.order(:created_at => :desc)
    elsif current_user.roles.any? { |r| r.name == 'Kadep Persediaan' }
      @sales = Sale.order(:created_at => :desc)
    end
  end

  # GET /sales/1 or /sales/1.json
  def show
    @sale_item = SaleItem.new
    @sale_items = SaleItem.where(sale_id: params[:id])
    @selected_items = ReceiveItem.find_by(id: params[:id])
    changeStatus(params[:id]) #Receive Helpers
    # @sale_items = SaleItem.includes(:receive_items)
  end

  # GET /sales/new
  def new
    @sale = Sale.new
    generate_sale_code
    # @kode_proyek = Receive.where(kode_proyek: get_project_commercial)
    # @dapet_kode = Sale.where(kode_proyek: @kode_proyek)
    # @get_kode_proyek =

    # @k = Receive.pluck(:kode_proyek)

    # @k = Receive.where('kode_proyek IN (?)',kode_proyek: Receive.pluck(:kode_proyek))
    # @k = Receive.where(kode_proyek: Receive.pluck(:kode_proyek))
  end




  def get_receive_data_nama_proyek
    kode_proyek = Receive.params[:id]
    nama_proyek = Receive.where(kode_proyek: kode_proyek)
    render :json => nama_proyek.try(:nama_proyek).to_json
  end

  # def get_receive_data_kode_akun
  #   kode_proyek = params[:id]
  #   kode_akun = Receive.find(kode_proyek)
  #   render :json => kode_akun.try(:kode_akun).to_json
  # end

  # GET /sales/1/edit
  def edit
    generate_sale_code
    # @nama_proyek_dari_penerimaan = Receive.distinct.pluck(:nama_proyek)

  end

  # POST /sales or /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        # Notification.create(notify_type: 'sale_draft', actor: current_user, user: current_user, target: @sale)
        if Sale.where(:status_id => 6)
          SaleMailer.sale_kepala_gudang.deliver_later
        end
        format.html { redirect_to @sale, notice: "Sale was successfully updated." }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1 or /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        # if Sale.where(:status_id => 6)
        #   SaleMailer.sale_kepala_gudang.deliver_later
        # end
        format.html { redirect_to @sale, notice: "Sale was successfully updated." }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1 or /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: "Sale was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def generate_sale_code
    get_day = DateTime.now.day.to_s
    get_month = DateTime.now.month.to_s
    get_year = DateTime.now.year.to_s
    @get_data_exists = Sale.all
    if @get_data_exists.empty?
      get_last_id = 001
      get_next_id = get_last_id
      @sale_code = "FO-#{get_day}-#{get_month}-#{get_year}-#{get_next_id}"
    else
      get_last_id = Sale.last.id
      get_next_id = get_last_id + 1
      @sale_code = "FO-#{get_day}-#{get_month}-#{get_year}-#{get_next_id}"
    end
  end


  # def getKodeBiaya
  #   uri = URI.parse('http://192.168.60.136:3000/fast/programs')
  #   http = Net::HTTP.new(uri.host, uri.port)
  #   http.use_ssl = false
  #   request = Net::HTTP::Get.new(uri.request_uri)
  #   request['Authorization'] = 'Bearer 4854b5b486f4159566c80d842850b967'
  #   response = http.request(request)
  #
  #   parsed = JSON.parse(response.body)
  #   render json: parsed
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_sale
    @sale = Sale.find(params[:id])
  end

    # Only allow a list of trusted parameters through.
  def sale_params
    params.require(:sale).permit(:nomor_penjualan, :tanggal_penjualan, :jenis_pengeluaran, :keterangan_penjualan,
                                 :nama_proyek, :kode_proyek, :kode_akun, :nama_akun, :status_id, :user_id, :nama_inputer,
                                 :catatan_penjualan, :receive_id, :kategori_kode, :status_approval, { dokumen_penjualan: [] })
  end
end

app/helpers/sales_helper.rb
module SalesHelper
    def changeStatus(id)
        @roleAssign = RoleAssignment.left_outer_joins(:user,:role).where(user_id: current_user.id).select('roles.id AS role_id')
        if @roleAssign.first.role_id.to_i == 2 #Admin Persediaan
            @setStatusBaca = Sale.find(id)
            if @setStatusBaca.status_id == 23
                SaleHistory.create!(
                    sale_id: id,
                    user_id: current_user.id,
                    status_id: 24,
                )
                @getPenerimaan = Sale.find(id)
                @getPenerimaan.update(status_id: 24)
            end
        elsif @roleAssign.first.role_id.to_i == 3 #Kadep Persediaan
            @setStatusBaca = Sale.find(id)
            if @setStatusBaca.status_id == 16
                SaleHistory.create!(
                    sale_id: id,
                    user_id: current_user.id,
                    status_id: 17,
                )
                @getPenerimaan = Sale.find(id)
                @getPenerimaan.update(status_id: 17)
            end
        elsif @roleAssign.first.role_id.to_i == 4 #Staff Gudang
            @setStatusBaca = Sale.find(id)
            if @setStatusBaca.status_id == 18
                SaleHistory.create!(
                    sale_id: id,
                    user_id: current_user.id,
                    status_id: 19,
                )
                @getPenerimaan = Sale.find(id)
                @getPenerimaan.update(status_id: 19)
            end
        elsif @roleAssign.first.role_id.to_i == 5 #Kepala Gudang
            @setStatusBaca = Sale.find(id)
            if @setStatusBaca.status_id == 20
                @getRecieveItem = SaleItem.where(sale_id: id)
                SaleHistory.create!(
                    sale_id: id,
                    status_id: 21,
                    user_id: current_user.id
                )
                @getPenerimaan = Sale.find(id)
                @getPenerimaan.update(status_id: 21)
            end
        end
    end
end

app/views/sales/edit.html.erb
<h1 class="my-5 text-center font-weight-bolder">Edit Pengeluaran Penjualan Barang</h1>

<%= render 'form', sale: @sale %>

<div class="mb-3 float-left">
  <%= link_to 'Back', sales_path, class:"btn btn-secondary text-white btn-custom rounded-pill" %>
</div>
</div>
</div>
</div>

app/views/sales/index.html.erb
<h1 class="my-5 text-center font-weight-bold text-primary">Pengeluaran Barang Penjualan</h1>

  <% if current_user.roles.any? { |r| r.name == "superadmin" || r.name == "User Trading" || r.name == "Admin Persediaan" } %>
    <div class="row mb-4">
      <div class="col-12 mt-3 d-flex justify-content-right">
        <%= link_to new_sale_path, class:"btn btn-primary btn-custom rounded-pill text" do %>
          <i id="my-icon" class="fas fa-plus"></i>
          <span>Pengeluaran</span>
        <% end %>
      </div>
    </div>
  <% end %>

<div class="row mx-0 px-2">

  <div class="table-responsive">
    <table class="table table-bordered" id="dataTable">
      <thead class="bg-primary">
      <tr class="text-center">
        <th class="align-middle" style="width: 13%;">Nomor Pengeluaran</th>
        <th class="align-middle" style="width: 14%;">Tanggal Pengeluaran</th>
        <th class="align-middle" id="keperluan_pengeluaran" style="width: 15%;">Keterangan Penjualan</th>
        <th class="align-middle" style="width: 15%;">Status</th>
        <th class="align-middle" style="width: 10%;">Inputer</th>
        <th class="align-middle" style="width: 20%;">Aksi</th>
      </tr>
      </thead>
      <tbody>
      <% if current_user.roles.any? { |r| r.name.match(/(Kadep Persediaan|Admin Persediaan|User Trading)/)} %>
        <% @sales.each do |sale| %>
          <%# warehouse = Warehouse.find_by(id: sale.warehouse) %>
          <% status = Status.find_by(id: sale.status) %>
          <% user = User.find_by(id: sale.user_id) %>
        <tr>
          <td class="align-middle text-center"> <%= sale.nomor_penjualan %> </td>
          <td class="align-middle text-center"> <%= sale.tanggal_penjualan %> </td>
          <td class="align-middle text-center"> <%= sale.catatan_penjualan %> </td>
          <td class="align-middle text-center">
            <% if status.try(:nama_status) == "draft" || status.try(:kategori) == "pending"%>
              <button class='btn btn-warning btn-sm py-1 mb-1 px-2' style="color: black;" disabled>
                <%= status.try(:nama_status) %>
              </button>
            <% elsif status.try(:kategori) == "reject" %>
              <button class='btn btn-danger btn-sm py-1 mb-1 px-2' style="color: black;" disabled>
                <%= status.try(:nama_status) %>
              </button>
            <% else%>
              <button class='btn btn-success btn-sm py-1 mb-1 px-2' style="color: black;" disabled>
                <%= status.try(:nama_status) %>
              </button>
            <% end %>
            </td>
          <td class="align-middle text-center"><%= user.try(:name) %> | <%= sale.nama_inputer %></td>
          <td class="align-middle text-center">
            <%= link_to sale,  class:"btn btn-info btn-sm rounded-circle text-white py-1 mb-1 px-2" do  %>
              <i class="fas fa-eye"></i>
            <% end %>
            <% if current_user.roles.any? { |r| r.name == "superadmin" || r.name == "User Trading" } %>
          <%= link_to edit_sale_path(sale),  class:"btn btn-warning btn-sm rounded-circle text-white py-1 mb-1 px-2" do  %>
              <i class="fas fa-pencil-alt"></i>
            <% end %>
              <% end %>
            <% if current_user.roles.any? { |r| r.name == "superadmin" || r.name == "User Trading" } %>
            <%= link_to sale, method: :delete, class:"btn btn-danger btn-sm rounded-circle text-white py-1 mb-1 px-2", data: { confirm: 'Are you sure?' } do %>
              <i class="fas fa-trash"></i>
            <% end %>
              <% end %>
            <% if current_user.roles.any? { |r| r.name == "superadmin" || r.name == "Kepala Gudang"  || r.name == "Admin Persediaan" || r.name == "Kepala Persediaan" } %>
          <%= link_to sale, method: :delete, class:"btn btn-dark btn-sm rounded-circle text-white py-1 mb-1 px-2", data: { confirm: 'Are you sure?' } do %>
              <i class="fas fa-download"></i>
              <% end %>
            <% end %>
          </td>
        <% end %>
      <% elsif current_user.roles.any? { |r| r.name.match(/(Staff Gudang|Kepala Gudang)/)} %>
        <% @sales.each do |sale| %>
          <%# warehouse = Warehouse.find_by(id: sale.warehouse) %>
          <% status = Status.find_by(id: sale.sale.status) %>
          <% user = User.find_by(id: sale.sale.user_id) %>
        <tr>
          <td class="align-middle text-center"> <%= sale.sale.nomor_penjualan %> </td>
          <td class="align-middle text-center"> <%= sale.sale.tanggal_penjualan %> </td>
          <td class="align-middle text-center"> <%= sale.sale.catatan_penjualan %> </td>
          <td class="align-middle text-center">
            <% if status.try(:nama_status) == "draft" || status.try(:kategori) == "pending"%>
              <button class='btn btn-warning btn-sm py-1 mb-1 px-2' style="color: black;" disabled>
                <%= status.try(:nama_status) %>
              </button>
            <% elsif status.try(:kategori) == "reject" %>
              <button class='btn btn-danger btn-sm py-1 mb-1 px-2' style="color: black;" disabled>
                <%= status.try(:nama_status) %>
              </button>
            <% else%>
              <button class='btn btn-success btn-sm py-1 mb-1 px-2' style="color: black;" disabled>
                <%= status.try(:nama_status) %>
              </button>
            <% end %>
            </td>
          <td class="align-middle text-center"><%= user.try(:name) %> | <%= sale.sale.nama_inputer %></td>
          <td class="align-middle text-center">
            <%= link_to sale_path(sale.sale_id),  class:"btn btn-info btn-sm rounded-circle text-white py-1 mb-1 px-2" do  %>
              <i class="fas fa-eye"></i>
            <% end %>
            <% if current_user.roles.any? { |r| r.name == "superadmin" || r.name == "User Trading" } %>
          <%= link_to edit_sale_path(sale.sale_id),  class:"btn btn-warning btn-sm rounded-circle text-white py-1 mb-1 px-2" do  %>
              <i class="fas fa-pencil-alt"></i>
            <% end %>
              <% end %>
            <% if current_user.roles.any? { |r| r.name == "superadmin" || r.name == "User Trading" } %>
            <%= link_to sale_path(sale.sale_id), method: :delete, class:"btn btn-danger btn-sm rounded-circle text-white py-1 mb-1 px-2", data: { confirm: 'Are you sure?' } do %>
              <i class="fas fa-trash"></i>
            <% end %>
              <% end %>
            <% if current_user.roles.any? { |r| r.name == "superadmin" || r.name == "Kepala Gudang"  || r.name == "Admin Persediaan" || r.name == "Kepala Persediaan" } %>
          <%= link_to sale_path(sale.sale_id), method: :delete, class:"btn btn-dark btn-sm rounded-circle text-white py-1 mb-1 px-2", data: { confirm: 'Are you sure?' } do %>
              <i class="fas fa-download"></i>
              <% end %>
            <% end %>
          </td>
        <% end %>
      <% end %>
      </tr>
      </tbody>
    </table>

  </div>
</div>
<br>

app/views/sales/new.html.erb
<h1 class="my-5 text-center font-weight-bolder">Input Pengeluaran Barang Penjualan</h1>

<%= render 'form', sale: @sale %>

<div class="mb-3 float-left">
  <%= link_to 'Kembali', sales_path, class:"btn btn-secondary text-white btn-custom rounded-pill" %>
</div>
</div>
</div>

app/views/sales/show.html.erb
<h1 class="my-5 text-center font-weight-bold text-primary">Pengeluaran Barang Penjualan</h1>

<div class="row mx-5 mb-3">
    <div class="col-12">
      <div class="navbar navbar-expand-sm menu-bar">
<!--        <ul class="navbar-nav border-bottom border-top w-100">-->
<!--          <li class="nav-item active">-->
<!--            <a class="nav-link" href="#">Data</a>-->
<!--          </li>-->
<!--          <li class="nav-item">-->
            <%#= link_to receives_path, class:"nav-link" do %>
<!--              <span>Barang</span>-->
            <%# end %>
<!--          </li>-->
<!--        </ul>-->
       <ul class="nav navbar-nav border-bottom border-top w-100" id="myTab" role="tablist">
          <li class="nav-item active" role="presentation">
            <a class="nav-link" id="receive-tab" data-toggle="tab" href="#sale-home" role="tab" aria-controls="sale-home" aria-selected="true" value="data">Data</a>
          </li>
          <li class="nav-item" role="presentation">
            <a class="nav-link" id="receive-item-tab" data-toggle="tab" href="#sale-item" role="tab" aria-controls="sale-item" aria-selected="false" value="barang">Barang</a>
          </li>
          <li class="nav-item" role="presentation">
            <a class="nav-link" id="receive-item-tab" data-toggle="tab" href="#sale_detail_status" role="tab" aria-controls="sale_detail_status" aria-selected="false" value="detail">Detail Status</a>
          </li>
        </ul>
      </div>
    </div>
  </div>

<div class="tab-content" id="myTabContent">
  <%= render "sales/tab_bars/data"%>
  <%= render "sales/tab_bars/barang"%>
  <%= render "sales/tab_bars/detail_status"%>

  <br>
  <div class="d-grid gap-2 d-md-flex mx-5 mb-3 justify-content-md-end">
    <%= render "sales/disposisi/user_trading" %>
    <%= render "sales/disposisi/staff_gudang" %>
  </div>
    <%= render "sales/disposisi/kepala_gudang" %>
    <%= render "sales/disposisi/admin_persediaan" %>
    <%= render "sales/disposisi/kadep_persediaan" %>
</div>
  
<script>
    $('li').click(function() {
        $('li.nav-item.active').removeClass("active");
        $(this).addClass("active");
    });
    
    $('#datatable-history').dataTable();

    document.getElementById("status-validate").required = true;
    
    $('#formvalidate').submit(function (e, params) {
            var localParams = params || {};

            if (!localParams.send) {
                e.preventDefault();
            }

                //additional input validations can be done hear

        swal({
                title: "Konfirmasi",
                text: "Anda yakin submit data ini ?",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#6A9944",
                confirmButtonText: "Iya",
                cancelButtonText: "Tidak",
                closeOnConfirm: true
            }, function (isConfirm) {
                if (isConfirm) {
                    $(e.currentTarget).trigger(e.type, { 'send': true });
                } else {

            //additional run on cancel  functions can be done hear

                }
        });
    });
</script>